x-common: &common
  build: 
    context: .
    dockerfile: Dockerfile
    args:
      - PW_VERSION=${PW_VERSION}
  init: true  # SysFlag (PID 1) No zomby
  ipc: host # Recommended for Chtomium repair leack of memory
  restart: unless-stopped
  working_dir: /app
  environment:
    - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright ##
#  volumes:
#    - playwright_browsers:/ms-playwright ##

services:
  dev1:
    <<: *common
    container_name: playwright_dev1
    ports:
      - "2221:22"
    volumes:
      - ./dev1:/app
      - playwright_browsers:/ms-playwright # folder with browsers, common for all DONT USE Template

  dev2:
    <<: *common
    container_name: playwright_dev2
    ports:
      - "2222:22"
    volumes:
      - ./dev2:/app
      - playwright_browsers:/ms-playwright

#  dev3:
#    <<: *common
#    container_name: playwright_dev3
#    ports: ["2223:22"]
#    volumes:
#      - ./dev3:/app"
#      - playwright_browsers:/ms-playwright

volumes:
  playwright_browsers:
    external: true


  # --- ДОПОЛНИТЕЛЬНЫЙ СЕРВИС для SHARED ---
  # Если нужно, чтобы shared была доступна как отдельный volume внутри контейнера,
  # можно смонтировать её дополнительно, но обычно достаточно симлинков.
  # В данном примере разработчики видят только свою папку (/app),
  # но могут получить доступ к shared через путь /opt/playwright/shared,
  # так как это host-path, или через симлинк внутри /app.