- targets:
    - "hyperdx-test.tivaliclub.com:9100"
  labels:
    env: "test"
    instance: "dashboards"

- targets:
    - "automation.local.tivaliclub.com:9100"
  labels:
    env: "test"
    instance: "automation"

- targets:
    - "dev.local.tivaliclub.com:9100"
  labels:
    env: "dev"
    instance: "development"

- targets:
    - "test.local.tivaliclub.com:9100"
  labels:
    env: "test"
    instance: "test"
