- targets:
    - "192.168.0.6:9100"
  labels:
    env: "test"
    instance: "prometeus-node"

- targets:
    - "192.168.0.5:9100"
  labels:
    env: "test"
    instance: "hyperdx-node"

- targets:
    - "10.130.0.26:9100"
  labels:
    env: "test"
    instance: "nat-node"
