version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - dbdata:/var/lib/postgresql/data

services:
  api:
    image: ://gitlab.com
    secrets:
      - db_password
    environment:
      # Tell .NET to look at the secret file path
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=mydb;Username=app;Password=/run/secrets/db_password

secrets:
  db_password:
    file: ./secrets/db_password



volumes:
  dbdata:
