services:

#=========Prometheus=====STORAGE==================
  prometheus:
    image: prom/prometheus:v3.11.2
    volumes:
      - ./prometheus/etc:/etc/prometheus/
      - ./prometheus/data:/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-15d}'
      - '--storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE:-20GB}'
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

#=========Node-Exporter==COLLECT=======================
  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: exporter
    #hostname: exporter
    network_mode: host  # Use host name
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave   
    
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs' #for correct disk size
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
#    ports:
#      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"


#=========Grafana=======================
  grafana:
    image: grafana/grafana:v13.0.0
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

#=======AlertManager======================
  alertmanager:
    image: prom/alertmanager:v0.31.1
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    container_name: alertmanager
    hostname: alertmanager
    # send host env to container ENV
    environment:
      TZ: "Europe/Moscow"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER_FROM: ${SMTP_USER_FROM}
      SMTP_LOGIN: ${SMTP_LOGIN}
      ALERT_EMAIL_TO: ${ALERT_EMAIL_TO}
      TG_CHAT_ID: ${TG_CHAT_ID}
    restart: unless-stopped
    # activate ENV support 
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
      - '--config.expand-env'

