services:

#=========Prometheus=====STORAGE==================
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/etc:/etc/prometheus/
      - ./prometheus/data:/prometheus
    container_name: prometheus
    hostname: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-15d}'
      - '--storage.tsdb.retention.size=${PROMETHEUS_RETENTION_SIZE:-20GB}'
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

#=========Node-Exporter==COLLECT=======================
  node-exporter:
    image: prom/node-exporter
    container_name: exporter
    #hostname: exporter
    network_mode: host  # Use host name
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave   
    
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs' #for correct disk size
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
#    ports:
#      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"


#=========Grafana=======================
  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

#=======AlertManager======================
  alertmanager:
    image: prom/alertmanager:v0.31.1
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    container_name: alertmanager
    hostname: alertmanager
    # send host env to container ENV
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    restart: unless-stopped
    # activate ENV support 
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/etc/alertmanager/data'
#      - '--config.expand-env=true'
    # activate ENV support 
    entrypoint:
      - /bin/sh
      - -c
      - |
        # IN Docker Compose use double $ ($$) for variables in section enviroment 
        sed -e "s|\$SMTP_HOST|$$SMTP_HOST|g" \
            -e "s|\$SMTP_USER_FROM|$$SMTP_USER_FROM|g" \
            -e "s|\$SMTP_LOGIN|$$SMTP_LOGIN|g" \
            -e "s|\$ALERT_EMAIL_TO|$$ALERT_EMAIL_TO|g" \
            -e "s|\$TELEGRAM_CHAT_ID|$$TELEGRAM_CHAT_ID|g" \
            /etc/alertmanager/alertmanager.yml.tmpl > /etc/alertmanager/alertmanager.yml &&
        exec /bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/etc/alertmanager/data




